#define LWIP_DBUG                            1
#define LWIP_DBG_MIN_LEVEL                   LWIP_DBG_LEVEL_ALL
#define DHCP_DEBUG                           LWIP_DBG_ON
#define UDP_DEBUG                            LWIP_DBG_ON
#define ETHARP_DEBUG                         LWIP_DBG_ON
#define PBUF_DEBUG                           LWIP_DBG_ON
#define IP_DEBUG                             LWIP_DBG_ON
#define TCPIP_DEBUG                          LWIP_DBG_ON
#define DHCP_DEBUG                           LWIP_DBG_ON
#define UDP_DEBUG                            LWIP_DBG_ON
#define LWIP_NETIF_LINK_CALLBACK             1
#define LWIP_NETIF_STATUS_CALLBACK           1     
#define LWIP_UDP                             1
#define LWIP_DHCP                            1
#define ETHARP_SUPPORT_STATIC_ENTRIES        1
#define LWIP_STATS                           1
#define ETHARP_STATS                         1
#define ARP_MAXAGE                           300000
#define ETHARP_STATS                          1
